linters:
  disable-all: false
  enable-all: true
  disable:
    # 2024-07 v0.59 - gomnd is reported deprecated / renamed
    # Deprecated
    - execinquery

    # Too annoying
    - exhaustruct # this is fine without, usually
    - funlen # somewhat ridiculous
    - cyclop # who cares! :D
    - godox # just leave it alone
    # TODO(apostasie) Temporary out until we wrap up all of them
    - wrapcheck

linters-settings:
  staticcheck:
    checks:
      - "all"

  depguard:
    rules:
      main:
        files:
          - "$all"
        allow:
          - $gostd
          - github.com/rs/zerolog
          - github.com/getsentry/sentry-go
          - github.com/google/uuid
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: we use Zerolog
          - pkg: "github.com/bugsnag/bugsnag-go"
            desc: we use Sentry
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package